[preview]
wrap = "no"
tab_size = 2

[opener]
extract = [
	{ run = 'ouch d -y "$@"', desc = "Extract here with ouch" },
]

[mgr]
ratio = [1, 3, 2]
sort_by = "natural"
sort_sensitive = true
sort_dir_first = true
show_hidden = true
show_symlink = true
scrolloff = 8

[plugin]
prepend_preloaders =	[
	{ mime = "{audio,video,image}/*", run = "mediainfo" },
	{ mime = "application/subrip", run = "mediainfo" },
	{ mime = "application/postscript", run = "mediainfo" },
]
prepend_previewers = [
	{ mime = "{audio,video,image}/*", run = "mediainfo"},
	{ mime = "application/subrip", run = "mediainfo" },
	{ mime = "application/postscript", run = "mediainfo" },

	{ mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
	{ mime = "application/vnd.rar",         run = "ouch" },
	{ mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },
	{ mime = "application/x-zstd",          run = "ouch" },
	{ mime = "application/zstd",            run = "ouch" },
	{ mime = "application/java-archive",    run = "ouch" },
]
